### ISSUE TITLE
Rules engine testing never finished and crashed on blackbox testing ARM platform for Fuji release

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/blackbox-testing#332]
Here is the build job.
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-fuji/

The rules engine test case was hanging and never finished. as a result the blackbox testing suite was crashed.

**Comment by judehung** [comment]
From the console output of those recent build failures(build#22 and build#24), both builds failed at the point when the response time of support-notifications ping test exceeds 800ms.

> support-notifications
11:19:09 
11:19:09 ❏ ping
11:19:09 ↳ Test service providing an indication that the service is available.
11:19:10   GET http://edgex-support-notifications:48060/api/v1/ping [200 OK, 105B, 827ms]
11:19:11   ✓  Status code is 200
11:19:11   1. Response time is less than 800ms
11:19:11   ✓  Content-Type is present
11:19:11   ✓  Content-Type is text/plain
11:19:11   ✓  Response body is correct
11:19:12 
11:19:12   #  failure         detail                                                                              
11:19:12                                                                                                          
11:19:12  1.  AssertionError  Response time is less than 800ms                                                    
11:19:12                      expected 827 to be below 800                                                        
11:19:12                      at assertion:1 in test-script                                                       
11:19:12                      inside "ping / Test service providing an indication that the service is available." 
11:19:13 Build step 'Execute shell' marked build as failure

For the successful build#23, the Jenkins job could be executed til the end when the response time of support-notification ping test is below 800ms.

It's strange that the entire Jenkins build was marked as failure for both build#22 and build#24 and skip the remaining testcases execution.

I'm going to setup an arm64 system to see what really happens when the response time of support-notifications ping test fails the assertion.

**Comment by cloudxxx8** [comment]
@lenny-intel could you or any application working group members help on this issue?
after we merge #341 , it sometimes works but still sometimes failed

**Comment by cherrycl** [comment]
Error log in rulesengine

```
14:11:56 #
14:11:56 # A fatal error has been detected by the Java Runtime Environment:
14:11:56 #
14:11:56 #  Internal Error (assembler_aarch64.hpp:1156), pid=6, tid=0x0000ffff7dc26a78
14:11:56 #  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
14:11:56 #
14:11:56 # JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
14:11:56 # Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
14:11:56 # Derivative: IcedTea 3.12.0
14:11:56 # Distribution: Custom build (Mon May  6 07:45:11 UTC 2019)
14:11:56 # Core dump written. Default location: /edgex/edgex-support-rulesengine/core or core.6
14:11:56 #
14:11:56 # An error report file with more information is saved as:
14:11:56 # /edgex/edgex-support-rulesengine/hs_err_pid6.log
14:11:56 [2019-12-13 06:10:09.067] boot - 6 ERROR [http-nio-48075-exec-7] --- runtime: Error executing FreeMarker template
14:11:56 FreeMarker template error:
14:11:56 The following has evaluated to null or missing:
14:11:56 ==> rulename  [in template "rule-template.drl" at line 7, column 9]
14:11:56 
14:11:56 ----
14:11:56 Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
14:11:56 ----
14:11:56 
14:11:56 ----
14:11:56 FTL stack trace ("~" means nesting-related):
14:11:56 	- Failed at: ${rulename}  [in template "rule-template.drl" at line 7, column 7]
14:11:56 ----
14:11:56 
14:11:56 Java stack trace (for programmers):
14:11:56 ----
14:11:56 freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
14:11:56 	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
14:11:56 	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:451)
14:11:56 	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:374)
14:11:56 	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:96)
14:11:56 	at freemarker.core.DollarVariable.accept(DollarVariable.java:59)
14:11:56 	at freemarker.core.Environment.visit(Environment.java:327)
14:11:56 	at freemarker.core.Environment.visit(Environment.java:333)
14:11:56 	at freemarker.core.Environment.process(Environment.java:306)
14:11:56 	at freemarker.template.Template.process(Template.java:386)
14:11:56 	at org.edgexfoundry.engine.RuleCreator.createDroolRule(RuleCreator.java:85)
14:11:56 	at org.edgexfoundry.controller.impl.RuleEngineControllerImpl.addRule(RuleEngineControllerImpl.java:64)
14:11:56 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:11:56 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:11:56 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:11:56 	at java.lang.reflect.Method.invoke(Method.java:498)
14:11:56 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
14:11:56 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
14:11:56 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
14:11:56 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832)
14:11:56 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743)
14:11:56 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
14:11:56 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
14:11:56 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
14:11:56 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
14:11:56 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
14:11:56 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
14:11:56 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
14:11:56 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
14:11:56 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
14:11:56 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
14:11:56 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
14:11:56 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
14:11:56 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
14:11:56 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
14:11:56 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
14:11:56 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
14:11:56 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
14:11:56 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
14:11:56 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
14:11:56 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
14:11:56 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
14:11:56 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
14:11:56 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
14:11:56 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
14:11:56 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
14:11:56 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
14:11:56 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
14:11:56 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
14:11:56 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
14:11:56 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:11:56 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:11:56 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
14:11:56 	at java.lang.Thread.run(Thread.java:748)
14:11:56 [2019-12-13 06:10:09.097] boot - 6 ERROR [http-nio-48075-exec-7] --- RuleCreator: Problem writing Drool rule.The following has evaluated to null or missing:
14:11:56 ==> rulename  [in template "rule-template.drl" at line 7, column 9]
14:11:56 
14:11:56 ----
14:11:56 Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
14:11:56 ----
14:11:56 
14:11:56 ----
14:11:56 FTL stack trace ("~" means nesting-related):
14:11:56 	- Failed at: ${rulename}  [in template "rule-template.drl" at line 7, column 7]
14:11:56 ----
14:11:56 [2019-12-13 06:10:09.114] boot - 6 ERROR [http-nio-48075-exec-7] --- RuleEngineControllerImpl: Problem adding a new rule called: null
14:11:56 #
14:11:56 # Compiler replay data is saved as:
14:11:56 # /edgex/edgex-support-rulesengine/replay_pid6.log
14:11:56 #
14:11:56 # If you would like to submit a bug report, please include
14:11:56 # instructions on how to reproduce the bug and visit:
14:11:56 #   https://icedtea.classpath.org/bugzilla
14:11:56 #
14:11:56 Aborted (core dumped)
```

**Comment by cloudxxx8** [comment]
@lenny-intel do you have any idea about the error log? thanks

**Comment by lenny-goodell** [comment]
Not really. Maybe @jpwhitemn can help as he is most familiar with the Rules Engine code.

The one line above that stands out is:
```
14:11:56 [2019-12-13 06:10:09.114] boot - 6 ERROR [http-nio-48075-exec-7] --- RuleEngineControllerImpl: Problem adding a new rule called: null
```
Seems the new rule being add is `null`???

**Comment by cherrycl** [comment]
The above JAVA Version error always showed on logs no matter rulesengine testcases passed or failed.

The following log only showed when rulesengine testcases passed. Rulesengine testcase failed seems the rules didn't create.

```
11:38:10 [2019-12-17 03:35:55.242] boot - 6  INFO [http-nio-48075-exec-9] --- RuleEngine: new rule:  motortoofastsignal added.
11:38:10 [2019-12-17 03:35:55.256] boot - 6  INFO [http-nio-48075-exec-9] --- RuleEngine: Starting Drools with drl files from:  /edgex/edgex-support-rulesengine/rules
11:38:10 [2019-12-17 03:35:55.268] boot - 6  INFO [http-nio-48075-exec-9] --- RuleEngine: Uploading Drool rules...
11:38:10 [2019-12-17 03:35:55.294] boot - 6  INFO [http-nio-48075-exec-9] --- RuleEngine: ... motortoofastsignal.drl
11:38:10 [2019-12-17 03:35:55.303] boot - 6  INFO [http-nio-48075-exec-9] --- RuleEngine: ... README
11:38:10 [2019-12-17 03:36:04.442] boot - 6  INFO [http-nio-48075-exec-9] --- KieRepositoryImpl: KieModule was added: MemoryKieModule[releaseId=org.default:artifact:1.0.0-SNAPSHOT]
11:38:10 [2019-12-17 03:36:04.806] boot - 6  INFO [http-nio-48075-exec-9] --- RuleEngineControllerImpl: Rule named:  motortoofastsignal added.
11:38:10 [2019-12-17 03:36:05.211] boot - 6  INFO [http-nio-48075-exec-1] --- RuleEngine: new rule:  motortoofastsignal added.
11:38:10 [2019-12-17 03:36:05.217] boot - 6  INFO [http-nio-48075-exec-1] --- RuleEngine: Starting Drools with drl files from:  /edgex/edgex-support-rulesengine/rules
11:38:10 [2019-12-17 03:36:05.224] boot - 6  INFO [http-nio-48075-exec-1] --- RuleEngine: Uploading Drool rules...
11:38:10 [2019-12-17 03:36:05.235] boot - 6  INFO [http-nio-48075-exec-1] --- RuleEngine: ... motortoofastsignal.drl
11:38:10 [2019-12-17 03:36:05.244] boot - 6  INFO [http-nio-48075-exec-1] --- RuleEngine: ... README
11:38:10 [2019-12-17 03:36:07.149] boot - 6  INFO [http-nio-48075-exec-1] --- KieRepositoryImpl: KieModule was added: MemoryKieModule[releaseId=org.default:artifact:1.0.0-SNAPSHOT]
11:38:10 [2019-12-17 03:36:07.420] boot - 6  INFO [http-nio-48075-exec-1] --- RuleEngineControllerImpl: Rule named:  motortoofastsignal added.
11:38:10 [2019-12-17 03:36:07.936] boot - 6  INFO [http-nio-48075-exec-4] --- RuleEngine: rule: motortoofastsignal removed.
11:38:10 [2019-12-17 03:36:07.939] boot - 6  INFO [http-nio-48075-exec-4] --- RuleEngineControllerImpl: Rule named:  motortoofastsignal removed
11:38:10 [2019-12-17 03:36:26.520] boot - 6 ERROR [http-nio-48075-exec-8] --- runtime: Error executing FreeMarker template
```

**Comment by cloudxxx8** [comment]
I noticed the major change between edinburgh and fuji is:
https://github.com/edgexfoundry/support-rulesengine/pull/53/files

We could try to revert the Dockerfile and see whether is can fix this issue

**Comment by cloudxxx8** [comment]
According to the decision in QA WG meeting on Dec-17-2019, we will remove the rules engine test on ARM in fuji

**Comment by cloudxxx8** [comment]
close this issue due to #365
