### ISSUE TITLE
Blackbox tests stalling on ARM64 - Fuji branch

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/blackbox-testing#370]
The following job is stalling after timeout. Happened 2 days in a row. I've submitted tickets for the LF to kill the job... but we need to root cause this issue.

https://jenkins.edgexfoundry.org/job/blackbox-testing-ubuntu18.04-docker-arm64-4c-2g-fuji/

Error Jan 1, 2020:
```
06:08:48 Build timed out (after 60 minutes). Marking the build as failed.
06:08:48 $ ssh-agent -k
06:08:48 unset SSH_AUTH_SOCK;
06:08:48 unset SSH_AGENT_PID;
06:08:48 echo Agent pid 1939 killed;
06:08:48 [ssh-agent] Stopped.
06:08:48 Build was aborted
06:08:48 Unpacking https://repo.jenkins-ci.org/maven-repo1/io/qameta/allure/allure-commandline/2.9.0/allure-commandline-2.9.0.zip to /w/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure_Report on prd-ubuntu18.04-docker-arm64-4c-2g-3891
06:10:00 An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
06:10:00 If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
06:10:00 Info: ExportClient's test data imported
06:10:00 Info: Initiating Export-Client Test.
06:10:00 [info] ---------- use docker-compose run newman ----------
```

Error Jan 3, 2020:
```
12:41:12 Build timed out (after 60 minutes). Marking the build as failed.
12:41:12 $ ssh-agent -k
12:41:12 unset SSH_AUTH_SOCK;
12:41:12 unset SSH_AGENT_PID;
12:41:12 echo Agent pid 1975 killed;
12:41:12 [ssh-agent] Stopped.
12:41:12 Build was aborted
12:41:13 Unpacking https://repo.jenkins-ci.org/maven-repo1/io/qameta/allure/allure-commandline/2.9.0/allure-commandline-2.9.0.zip to /w/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure_Report on prd-ubuntu18.04-docker-arm64-4c-2g-4269
12:42:24 An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
12:42:24 If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
12:42:25 ./run.sh: line 66: 18463 Terminated              $(dirname "$0")/supportNotificationsTest.sh
12:42:25 ./run.sh: line 131: 10195 Exit 143                testAll
12:42:25      10196 Terminated              | tee $EDGEXLOGSPATH
12:42:30 The SECURITY_IS_ON variable is not set. Defaulting to a blank string.
12:44:30 An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
12:44:30 If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).```

**Comment by bnevis-i** [comment]
Do you believe this is infrastructural or a code issue?

**Comment by cloudxxx8** [comment]
@lranjbar @bnevis-i it sometimes happens, and will be gone after restart the job.  Let's see whether it keeps existing. The Jenkins nodes are all offline right now.

**Comment by lranjbar** [comment]
Code because it has happened twice in a row last week. There are other issues going on with Jenkins that are being made worse by this job stalling out.

**Comment by bnevis-i** [comment]
Here is where these tests are failing.  They seem to be getting quite far along with passing tests before eventually getting stuck.  No timestamps or container logs during the test run to see if there are containers failing halfway through.

...
Initiating Support Notifications Test // build 77 (Jan 3) - terminated
Initiating Export-Client Test // build 76 (Jan 1) - terminated
Initiating Support-Scheduler Test
END // build 75 (Dec 31) - successful (27 min)

**Comment by bnevis-i** [comment]
The tail of both of the failed jobs ends with:

```
Build timed out (after 60 minutes). Marking the build as failed.
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 1975 killed;
[ssh-agent] Stopped.
Build was aborted
Unpacking https://repo.jenkins-ci.org/maven-repo1/io/qameta/allure/allure-commandline/2.9.0/allure-commandline-2.9.0.zip to /w/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure_Report on prd-ubuntu18.04-docker-arm64-4c-2g-4269
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
./run.sh: line 66: 18463 Terminated              $(dirname "$0")/supportNotificationsTest.sh
./run.sh: line 131: 10195 Exit 143                testAll
     10196 Terminated              | tee $EDGEXLOGSPATH
The SECURITY_IS_ON variable is not set. Defaulting to a blank string.
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ERROR: Step ‘Allure Report’ aborted due to exception: 
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.Channel.call(Channel.java:956)
	at hudson.FilePath.act(FilePath.java:1072)
	at hudson.FilePath.act(FilePath.java:1061)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:915)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:848)
	at hudson.tools.DownloadFromUrlInstaller.performInstallation(DownloadFromUrlInstaller.java:77)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:69)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:206)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.forNode(AllureCommandlineInstallation.java:108)
	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.forNode(AllureCommandlineInstallation.java:33)
	at ru.yandex.qatools.allure.jenkins.utils.BuildUtils.setUpTool(BuildUtils.java:39)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:353)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:303)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1840)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

If the timeout condition was successfully detected
`Build timed out (after 60 minutes). Marking the build as failed.`
then why does the job continue to drag on until it is manually killed.

It looks to me like the test hangs for some network-related reason, the 60 minute timeout kicks in, and then the reporting step hangs and is eventually (manually) killed.

**Comment by cloudxxx8** [comment]
The report is built in Jenkins post-procedure, so the timeout mechanism isn't applied to it

**Comment by bnevis-i** [comment]
> The report is built in Jenkins post-procedure, so the timeout mechanism isn't applied to it

Is that lending evidence to support that it is actually the post-procedure that is hanging rather than the tests themselves?  Or maybe both, and post-procedure hanging is that is making this fatal rather an a recoverable error?

**Comment by lranjbar** [comment]
So now we are a few days out of the network issues from the LF resolving and these builds are working as intended again. Thanks Cloud and Bryon for looking into it. @cloudxxx8 @bnevis-i

**Comment by cloudxxx8** [comment]
@bnevis-i the whole allure report is built during post-procedure.  However, it's hard to reproduce.  We will open another issue to improve it if it keeps happening.
